import { useEffect, useState } from "react";
import Topbar from "../components/Topbar";
import { createEngineerReport, getEngineerReports } from "../services/fieldServices";

export default function EngineerReportsPage() {
  const [reports, setReports] = useState([]); const [form, setForm] = useState({ titre: "", contenu: "", periode_debut: "", periode_fin: "" }); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const refresh = async () => { try { setReports(await getEngineerReports()); } catch(e){ setError(e.message); } }; useEffect(()=>{refresh()},[]);
  const submit = async e => { e.preventDefault(); setError(""); setSuccess(""); try { await createEngineerReport(form); setSuccess("Rapport technique soumis au Chef de projet."); setForm({titre:"",contenu:"",periode_debut:"",periode_fin:""}); refresh(); } catch(e){setError(e.message)} };
  return <div className="app-shell"><Topbar/><main className="page-wrap"><div className="page-grid-2"><section className="page-card"><div className="page-heading"><div><span className="eyebrow">Ingénieur</span><h1>Nouveau rapport technique</h1></div></div><form className="form-grid" onSubmit={submit}><div className="field"><label>Titre</label><input value={form.titre} onChange={e=>setForm({...form,titre:e.target.value})} required/></div><div className="field-row"><div className="field"><label>Début</label><input type="date" value={form.periode_debut} onChange={e=>setForm({...form,periode_debut:e.target.value})}/></div><div className="field"><label>Fin</label><input type="date" value={form.periode_fin} onChange={e=>setForm({...form,periode_fin:e.target.value})}/></div></div><div className="field"><label>Contenu</label><textarea rows="8" value={form.contenu} onChange={e=>setForm({...form,contenu:e.target.value})} required/></div><button type="submit">Soumettre le rapport</button></form>{error&&<div className="alert-box danger">{error}</div>}{success&&<div className="alert-box success">{success}</div>}</section><section className="page-card"><h2>Mes rapports</h2><div className="card-list">{reports.map(r=><article className="item-card" key={r.id}><div><strong>{r.titre}</strong><p>Statut : {r.statut}</p></div><span className="status-pill">{r.type}</span></article>)}{!reports.length&&<p>Aucun rapport.</p>}</div></section></div></main></div>;
}
